/**
 * Generates seed-generated.sql from seed-data/*.json
 * Run: node scripts/seed-d1.mjs
 * Then: npm run seed  (writes to remote D1)
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root = join(__dirname, '..')

function sqlStringLiteral(obj) {
  return "'" + JSON.stringify(obj).replace(/'/g, "''") + "'"
}

function normalizeHabits(h) {
  const goals = { ...h.goals }
  if (goals.lifting) {
    goals.lift = { ...goals.lifting, label: goals.lifting.label === 'Lifting' ? 'Lift' : goals.lifting.label }
    delete goals.lifting
  }
  const logs = {}
  for (const [k, day] of Object.entries(h.logs || {})) {
    const d = { ...day }
    if ('lifting' in d && !('lift' in d)) {
      d.lift = d.lifting
      delete d.lifting
    }
    logs[k] = d
  }
  return {
    goals,
    logs,
    appSettings: h.appSettings || { firstDayOfWeek: 0 },
  }
}

const habitsRaw = JSON.parse(readFileSync(join(root, 'seed-data/checkmark.json'), 'utf8'))
const macroRaw = JSON.parse(readFileSync(join(root, 'seed-data/macro.json'), 'utf8'))
const liftRaw = JSON.parse(readFileSync(join(root, 'seed-data/lift.json'), 'utf8'))

const habits = normalizeHabits(habitsRaw)
const now = Date.now()
const device = 'default'
const selectedDate = new Date().toISOString().slice(0, 10)

const sql = `-- generated by scripts/seed-d1.mjs
DELETE FROM app_state WHERE device_id = '${device}';
DELETE FROM habits_bundle WHERE device_id = '${device}';
DELETE FROM macro_bundle WHERE device_id = '${device}';
DELETE FROM lift_bundle WHERE device_id = '${device}';

INSERT INTO app_state (
  device_id, selected_tab, settings_open, settings_section,
  lift_sub_route, lift_selected_day_id, lift_current_day_index,
  selected_date, updated_at
) VALUES (
  '${device}',
  'habits',
  0,
  'habits',
  'workout',
  NULL,
  0,
  '${selectedDate}',
  ${now}
);

INSERT INTO habits_bundle (device_id, goals_json, logs_json, app_settings_json, updated_at)
VALUES (
  '${device}',
  ${sqlStringLiteral(habits.goals)},
  ${sqlStringLiteral(habits.logs)},
  ${sqlStringLiteral(habits.appSettings)},
  ${now}
);

INSERT INTO macro_bundle (device_id, goals_json, custom_foods_json, logs_json, updated_at)
VALUES (
  '${device}',
  ${sqlStringLiteral(macroRaw.goals)},
  ${sqlStringLiteral(macroRaw.customFoods)},
  ${sqlStringLiteral(macroRaw.logs)},
  ${now}
);

INSERT INTO lift_bundle (device_id, payload_json, updated_at)
VALUES (
  '${device}',
  ${sqlStringLiteral(liftRaw)},
  ${now}
);
`

writeFileSync(join(root, 'seed-generated.sql'), sql)
console.log('Wrote seed-generated.sql')
